-- ================================================================
-- Pulso — seed do estoque inicial (GIO e Sorridents)
--
-- Popula a tabela estoque_itens com os itens que já existiam nas
-- planilhas de controle de estoque das duas clínicas. Rode isso UMA vez,
-- depois de já ter rodado o schema.sql. Se precisar reimportar do zero,
-- apague as linhas antigas primeiro:
--   delete from public.estoque_itens;
-- ================================================================

insert into public.estoque_itens (clinica_id, categoria, nome, quantidade_ideal, quantidade_atual) values
  ('gio', 'Área Técnica - Diversos', 'Agulha 30g', 100, 20),
  ('gio', 'Área Técnica - Diversos', 'Agulha 18g', 100, 20),
  ('gio', 'Área Técnica - Diversos', 'Palito Madeira para Laser', 100, 50),
  ('gio', 'Área Técnica - Diversos', 'Lençol Maca Descartável - 70x50 (grande)', 35, 34),
  ('gio', 'Área Técnica - Diversos', 'Cartucho micro 36 ( smart)', 20, 12),
  ('gio', 'Área Técnica - Diversos', 'Luvas Vinil M', 10, 10),
  ('gio', 'Área Técnica - Diversos', 'Gel Condutor 5kg', 10, 9),
  ('gio', 'Área Técnica - Diversos', 'Canula 18gx70mm', 5, 2),
  ('gio', 'Área Técnica - Diversos', 'Álcool Liquido 70%', 2, 0),
  ('gio', 'Área Técnica - Diversos', 'Esfoliante facial', 2, 0),
  ('gio', 'Área Técnica - Diversos', 'Gel de limpeza facial', 2, 0),
  ('gio', 'Área Técnica - Diversos', 'Máscara facial', 2, 0),
  ('gio', 'Área Técnica - Diversos', 'Protetor solar facial', 2, 0),
  ('gio', 'Área Técnica - Diversos', 'Tônico facial', 2, 0),
  ('gio', 'Área Técnica - Diversos', 'Gaze Compressa', 2, 0),
  ('gio', 'Área Técnica - Diversos', 'Creme de massagem Pimenta Dagua Natural 1L', 2, 1),
  ('gio', 'Área Técnica - Diversos', 'Babador odontológico', 1, 0),
  ('gio', 'Área Técnica - Diversos', 'Creme de massagem Neutro Dagua Natural 1L', 6, 5),
  ('gio', 'Área Técnica - Diversos', 'Emoliente', 1, 0),
  ('gio', 'Área Técnica - Diversos', 'Luvas Latéx P', 3, 2),
  ('gio', 'Área Técnica - Diversos', 'Micropore', 2, 1),
  ('gio', 'Área Técnica - Diversos', 'Touca', 2, 2),
  ('gio', 'Área Técnica - Diversos', 'Clorexidina Alcoólica 2%', 1, 1),
  ('gio', 'Área Técnica - Diversos', 'Descarpack 7l', 2, 2),
  ('gio', 'Área Técnica - Diversos', 'Papel filme', 1, 1),
  ('gio', 'Área Técnica - Diversos', 'Água Destilada - Laser', 1, 1),
  ('gio', 'Área Técnica - Diversos', 'Água para injetáveis', 1, 1),
  ('gio', 'Área Técnica - Diversos', 'Canula 22g 50mm', 10, 10),
  ('gio', 'Área Técnica - Diversos', 'Cureta descartável', 20, 20),
  ('gio', 'Área Técnica - Diversos', 'Lenço Umidecido', 8, 8),
  ('gio', 'Área Técnica - Diversos', 'Lidocaina 2% sem vaso', 10, 10),
  ('gio', 'Área Técnica - Diversos', 'Máscara Descartável', 2, 2),
  ('gio', 'Área Técnica - Diversos', 'Mascara desidratada', 2, 2),
  ('gio', 'Área Técnica - Diversos', 'Seringa 10ml luerlock', 30, 30),
  ('gio', 'Área Técnica - Diversos', 'Seringa 1ml', 100, 100),
  ('gio', 'Área Técnica - Diversos', 'Seringa 5ml luerlock', 50, 50),
  ('gio', 'Área Técnica - Diversos', 'Seringa botox 50ui', 50, 50),
  ('gio', 'Área Técnica - Diversos', 'Soro para injetáveis - cloreto de sódio esteril 10ml (0,9)', 15, 15),
  ('gio', 'Área Técnica - Diversos', 'Creme calmante facial', 0, 1),
  ('gio', 'Área Técnica - Diversos', 'Mantas da crio', 30, 36),
  ('gio', 'Invasivos', 'RENNOVA Preenchedor Ultravolume', 8, 8),
  ('gio', 'Invasivos', 'Ativo Micro Ácido Tranexâmico', 10, 0),
  ('gio', 'Invasivos', 'RENNOVA Preenchedor Lift', 15, 12),
  ('gio', 'Invasivos', 'RENNOVA Bioestimulador Diamond', 4, 4),
  ('gio', 'Invasivos', 'PHD Pump Glúteos', 2, 2),
  ('gio', 'Invasivos', 'Nabota 100 ui', 10, 7),
  ('gio', 'Invasivos', 'PHD Enzimas papada', 2, 2),
  ('gio', 'Invasivos', 'GALDERMA Sculptra', 4, 3),
  ('gio', 'Invasivos', 'PHD Enzimas mescla perda de peso II', 1, 1),
  ('gio', 'Invasivos', 'PHD Hialuronidase', 1, 0),
  ('gio', 'Invasivos', 'Ativo Micro Capilar', 5, 5),
  ('gio', 'Invasivos', 'PHD GL light 2', 2, 1),
  ('gio', 'Invasivos', 'Ativo Micro Ácido Hialurônico', 5, 5),
  ('gio', 'Invasivos', 'PHD Glicose 75%', 5, 29),
  ('gio', 'Serviços Gerais', 'Chá', 8, 2),
  ('gio', 'Serviços Gerais', 'Copo Café 80ml', 4, 0),
  ('gio', 'Serviços Gerais', 'Café', 5, 2),
  ('gio', 'Serviços Gerais', 'Filtro Café 103', 5, 2),
  ('gio', 'Serviços Gerais', 'Papel Higiênico', 4, 1),
  ('gio', 'Serviços Gerais', 'Detergente Louça', 2, 0),
  ('gio', 'Serviços Gerais', 'Saco Lixo 50L PRETO', 2, 0),
  ('gio', 'Serviços Gerais', 'Saco Lixo 50L Azul', 2, 0),
  ('gio', 'Serviços Gerais', 'Açucar 1kg', 2, 0),
  ('gio', 'Serviços Gerais', 'Vanish', 1, 0),
  ('gio', 'Serviços Gerais', 'Pano Perfex', 1, 0),
  ('gio', 'Serviços Gerais', 'Limpa Vidros', 1, 0),
  ('gio', 'Serviços Gerais', 'Sapoli', 1, 0),
  ('gio', 'Serviços Gerais', 'Sabão em Liquido BRILHANTE', 1, 1),
  ('gio', 'Serviços Gerais', 'Amaciante', 1, 1),
  ('gio', 'Serviços Gerais', 'Pano de Chão', 3, 3),
  ('gio', 'Serviços Gerais', 'Papel Toalha Rolo', 1, 1),
  ('gio', 'Serviços Gerais', 'Esponja', 1, 1),
  ('gio', 'Serviços Gerais', 'Desinfetante', 3, 3),
  ('gio', 'Serviços Gerais', 'Água Sanitária', 1, 1),
  ('gio', 'Serviços Gerais', 'Saco Lixo 100L', 1, 1),
  ('gio', 'Serviços Gerais', 'Sabonete Liquido', 2, 3),
  ('gio', 'Serviços Gerais', 'Saco de Lixo BRANCO (biológico)', 0, 2),
  ('gio', 'Serviços Gerais', 'Papel Toalha Interfolhas', 25, 80),
  ('sorridents', 'Cirurgia', 'Seringa 20ml Com Agulha', 10, 0),
  ('sorridents', 'Cirurgia', 'Campo Cirúrgico Completo', 10, 4),
  ('sorridents', 'Cirurgia', 'Luva Cirúrgica Estéril 7.5', 10, 6),
  ('sorridents', 'Cirurgia', 'Articaína', 4, 0),
  ('sorridents', 'Cirurgia', 'Lidocaina', 5, 1),
  ('sorridents', 'Cirurgia', 'Broca Zecrya', 3, 0),
  ('sorridents', 'Cirurgia', 'Fio De Nylon 4.0', 5, 3),
  ('sorridents', 'Cirurgia', 'Soro Fisiologico', 3, 1),
  ('sorridents', 'Cirurgia', 'Anestésico Tópico', 3, 2),
  ('sorridents', 'Cirurgia', 'Enxerto Nanosynt', 2, 1),
  ('sorridents', 'Cirurgia', 'Lamina De Bisturi 15', 1, 0),
  ('sorridents', 'Cirurgia', 'Sugador Cirúrgico Cx 40 Uni', 1, 0),
  ('sorridents', 'Cirurgia', 'Clorexidina 0,12%', 1, 0),
  ('sorridents', 'Cirurgia', 'Agulha Gengival 27g Longa', 1, 0),
  ('sorridents', 'Cirurgia', 'Hemospon', 1, 0),
  ('sorridents', 'Cirurgia', 'Agulha Gengival 30g Curta', 2, 2),
  ('sorridents', 'Cirurgia', 'Broca 702 para peça reta', 2, 4),
  ('sorridents', 'Dentística', 'Acido Fosfórico 37%', 10, 5),
  ('sorridents', 'Dentística', 'Tira de Lixa De Poliéster Abrasiva', 4, 0),
  ('sorridents', 'Dentística', 'Microaplicador regular', 5, 2),
  ('sorridents', 'Dentística', 'Papel Carbono', 5, 2),
  ('sorridents', 'Dentística', 'Resina Master Flow - Biodinâmica A2', 6, 3),
  ('sorridents', 'Dentística', 'Tira de Lixa Aço', 3, 0),
  ('sorridents', 'Dentística', 'Adesivo 3M', 4, 3),
  ('sorridents', 'Dentística', 'Resina A3', 2, 1),
  ('sorridents', 'Dentística', 'Kit Polimento De Resina', 2, 2),
  ('sorridents', 'Dentística', 'Banda Matriz O5x5', 1, 1),
  ('sorridents', 'Dentística', 'Banda Matriz O5x7', 1, 1),
  ('sorridents', 'Dentística', 'Ionomero Fotopolimerizavel', 1, 1),
  ('sorridents', 'Dentística', 'cunha de madeira', 1, 1),
  ('sorridents', 'Dentística', 'Resina A2', 3, 3),
  ('sorridents', 'Dentística', 'Resina A3.5', 2, 2),
  ('sorridents', 'Dentística', 'Pasta De Polimento', 1, 2),
  ('sorridents', 'Dentística', 'Resina B2', 1, 2),
  ('sorridents', 'Dentística', 'Tira De Poliester', 4, 7),
  ('sorridents', 'Dentística', 'Resina A1', 2, 5),
  ('sorridents', 'Descartáveis', 'Luva Xp', 32, 10),
  ('sorridents', 'Descartáveis', 'Rolete De Algodão', 20, 7),
  ('sorridents', 'Descartáveis', 'Sugador', 20, 8),
  ('sorridents', 'Descartáveis', 'Babador', 16, 7),
  ('sorridents', 'Descartáveis', 'Controle Autoclave (Indicador Biológico)', 8, 0),
  ('sorridents', 'Descartáveis', 'Gaze', 8, 4),
  ('sorridents', 'Descartáveis', 'Máscaras Descartáveis', 4, 1),
  ('sorridents', 'Descartáveis', 'Revelador', 3, 1),
  ('sorridents', 'Descartáveis', 'Fixador', 3, 1),
  ('sorridents', 'Descartáveis', 'Grau 80mmx100m', 2, 0),
  ('sorridents', 'Descartáveis', 'Grau esterilização 50mmx100m', 3, 2),
  ('sorridents', 'Descartáveis', 'Ficha de raio X 2 espacos adulto', 2, 1),
  ('sorridents', 'Descartáveis', 'Touca', 1, 0),
  ('sorridents', 'Descartáveis', 'Filme Rx (Adulto) E-Speed (Carestream)', 1, 0),
  ('sorridents', 'Descartáveis', 'Fio dental grande', 2, 1),
  ('sorridents', 'Descartáveis', 'Ficha de Raio X 2 espacos infantil', 1, 0),
  ('sorridents', 'Descartáveis', 'Descarpack 3L', 4, 3),
  ('sorridents', 'Descartáveis', 'Controle Autoclave (Químico)', 3, 3),
  ('sorridents', 'Descartáveis', 'Fita Para Autoclave', 1, 1),
  ('sorridents', 'Descartáveis', 'Filme Rx (Infantil )', 1, 1),
  ('sorridents', 'Descartáveis', 'Detergente Zymedet Gold', 1, 1),
  ('sorridents', 'Descartáveis', 'Grau 150 mm x100m', 2, 3),
  ('sorridents', 'Descartáveis', 'Luva P', 17, 32),
  ('sorridents', 'Endodontia', 'seringa 10 ml luerlock sem agulha (rosca)', 6, 0),
  ('sorridents', 'Endodontia', 'lima flex serie especial n 10 de 21 mm', 2, 0),
  ('sorridents', 'Endodontia', 'lima flex serie especial n 8 de 21 mm', 2, 0),
  ('sorridents', 'Endodontia', 'Sugador Endodôntico', 3, 1),
  ('sorridents', 'Endodontia', 'Lençol de borracha', 2, 1),
  ('sorridents', 'Endodontia', 'Obturador provisório', 2, 1),
  ('sorridents', 'Endodontia', 'Ponta papel absorvente N 25', 1, 0),
  ('sorridents', 'Endodontia', 'Guta Recipro 25.08 TANARI', 1, 0),
  ('sorridents', 'Endodontia', 'Endofill (pó)', 1, 1),
  ('sorridents', 'Endodontia', 'Ponta de Papel absorvente N 40', 1, 1),
  ('sorridents', 'Endodontia', 'Alveolex', 1, 1),
  ('sorridents', 'Endodontia', 'Endofil (líquido)', 1, 1),
  ('sorridents', 'Endodontia', 'Eugenol (líquido)', 1, 1),
  ('sorridents', 'Endodontia', 'tricresolformalina', 1, 1),
  ('sorridents', 'Endodontia', 'EDTA', 1, 2),
  ('sorridents', 'Endodontia', 'Formocresol', 1, 2),
  ('sorridents', 'Endodontia', 'Agulha irrigação 27G x 25mm com saída lateral', 5, 35),
  ('sorridents', 'Ortodontia', 'Tubo de colagem 16/17 sup', 1, 0),
  ('sorridents', 'Ortodontia', 'Tubo de colagem 26/27 sup', 1, 0),
  ('sorridents', 'Ortodontia', 'Tubo de colagem 36/37 infer', 1, 0),
  ('sorridents', 'Ortodontia', 'Tubo de colagem 46/47 infer', 1, 0),
  ('sorridents', 'Ortodontia', 'Braquetes Cerâmicos', 4, 2),
  ('sorridents', 'Ortodontia', 'Fio Niti 014u', 3, 1),
  ('sorridents', 'Ortodontia', 'Fio Niti 018l', 4, 1),
  ('sorridents', 'Ortodontia', 'Fio Niti 012 L', 3, 1),
  ('sorridents', 'Ortodontia', 'Fio Niti 014l', 3, 1),
  ('sorridents', 'Ortodontia', 'Fio Niti 018u', 4, 2),
  ('sorridents', 'Ortodontia', 'Elástico Intra Oral Médio 1/8', 3, 1),
  ('sorridents', 'Ortodontia', 'Fio Aço 016l', 2, 0),
  ('sorridents', 'Ortodontia', 'Fio Aço 016u', 2, 0),
  ('sorridents', 'Ortodontia', 'Fio Aço 020l', 2, 0),
  ('sorridents', 'Ortodontia', 'Fio Aço 020u', 2, 0),
  ('sorridents', 'Ortodontia', 'Fio Niti 016l', 3, 1),
  ('sorridents', 'Ortodontia', 'Fio Aço 018u', 2, 0),
  ('sorridents', 'Ortodontia', 'Fio Aço 016x022u', 2, 0),
  ('sorridents', 'Ortodontia', 'Bengalinha Azul Marinho', 2, 0),
  ('sorridents', 'Ortodontia', 'Elástico em Cadeia Médio Azul Bêbe', 2, 1),
  ('sorridents', 'Ortodontia', 'Elástico em Cadeia Médio Azul Marinho', 2, 1),
  ('sorridents', 'Ortodontia', 'Fio Niti 012u', 3, 2),
  ('sorridents', 'Ortodontia', 'Botão língual cola', 2, 1),
  ('sorridents', 'Ortodontia', 'Bengalinha Vinho', 2, 1),
  ('sorridents', 'Ortodontia', 'Fio Aço 018l', 2, 1),
  ('sorridents', 'Ortodontia', 'Embalagem P/Elasticos', 2, 1),
  ('sorridents', 'Ortodontia', 'Fio Aço 016x022l', 2, 1),
  ('sorridents', 'Ortodontia', 'Braquetes metálicos embalagem econômica', 1, 0),
  ('sorridents', 'Ortodontia', 'Cimento orthocem', 5, 4),
  ('sorridents', 'Ortodontia', 'Fio de contenção Twistform', 2, 1),
  ('sorridents', 'Ortodontia', 'Elástico em Cadeia Médio pearl blue', 2, 2),
  ('sorridents', 'Ortodontia', 'Elástico em Cadeia Médio Azul', 2, 2),
  ('sorridents', 'Ortodontia', 'Elástico em Cadeia Médio Cinza', 2, 2),
  ('sorridents', 'Ortodontia', 'Elastico em Cadeia Medio azul cristal', 2, 2),
  ('sorridents', 'Ortodontia', 'Fio Niti 016u', 3, 3),
  ('sorridents', 'Ortodontia', 'Caixa Para Aparelho', 2, 2),
  ('sorridents', 'Ortodontia', 'Elástico Intra Oral Médio 5/16', 3, 3),
  ('sorridents', 'Ortodontia', 'Bengalinha Azul Cristal', 2, 2),
  ('sorridents', 'Ortodontia', 'Bengalinha Prata', 2, 2),
  ('sorridents', 'Ortodontia', 'Elástico em Cadeia Médio Cristal', 2, 2),
  ('sorridents', 'Ortodontia', 'Elástico em Cadeia Médio Prata', 2, 2),
  ('sorridents', 'Ortodontia', 'Elástico em Cadeia Médio Roxo', 2, 2),
  ('sorridents', 'Ortodontia', 'Gancho Bola', 2, 2),
  ('sorridents', 'Ortodontia', 'Mola Aberta de NITI', 1, 2),
  ('sorridents', 'Ortodontia', 'Fio Niti 020 L', 4, 5),
  ('sorridents', 'Ortodontia', 'Elástico em Cadeia Médio Vermelho', 2, 3),
  ('sorridents', 'Ortodontia', 'Fio Niti 020 U', 4, 5),
  ('sorridents', 'Ortodontia', 'Elástico em Cadeia Médio Preto', 2, 4),
  ('sorridents', 'Ortodontia', 'Bengalinha pearl blue', 2, 4),
  ('sorridents', 'Ortodontia', 'Elastico em cadeia Medio Rosa', 2, 4),
  ('sorridents', 'Ortodontia', 'Elástico em Cadeia Médio Verde Mar', 2, 4),
  ('sorridents', 'Ortodontia', 'Braquete Autoligado', 3, 5),
  ('sorridents', 'Ortodontia', 'Bengalinha Azul Bebê', 2, 5),
  ('sorridents', 'Ortodontia', 'Bengalinha Lilás', 2, 5),
  ('sorridents', 'Ortodontia', 'Elástico em Cadeia Médio Lilás', 2, 5),
  ('sorridents', 'Ortodontia', 'Bengalinha Azul', 2, 6),
  ('sorridents', 'Ortodontia', 'Bengalinha Cinza', 2, 6),
  ('sorridents', 'Ortodontia', 'Separador', 2, 6),
  ('sorridents', 'Ortodontia', 'Bengalinha Preto', 3, 7),
  ('sorridents', 'Ortodontia', 'Elástico Intra Oral Médio 3/16', 3, 8),
  ('sorridents', 'Ortodontia', 'Elástico em Cadeia Médio Vinho', 2, 7),
  ('sorridents', 'Ortodontia', 'Elastico Intra Oral 1/8 Pesado', 2, 8),
  ('sorridents', 'Ortodontia', 'Bengalinha Cristal', 2, 8),
  ('sorridents', 'Ortodontia', 'Bengalinha Roxo', 2, 8),
  ('sorridents', 'Ortodontia', 'Bengalinha Verde Mar', 2, 8),
  ('sorridents', 'Ortodontia', 'Bengalinha Rosa', 2, 10),
  ('sorridents', 'Ortodontia', 'Bengalinha Vermelha', 2, 11),
  ('sorridents', 'Ortodontia', 'Bengalinha Verde Cristal', 2, 14),
  ('sorridents', 'Profilaxia e claramento', 'Escova Robson', 10, 5),
  ('sorridents', 'Profilaxia e claramento', 'Barreira gengival', 6, 2),
  ('sorridents', 'Profilaxia e claramento', 'Clareador peróxido carbamida 16%', 8, 7),
  ('sorridents', 'Profilaxia e claramento', 'Pasta profilática', 4, 4),
  ('sorridents', 'Profilaxia e claramento', 'Placa EVA 1mm', 2, 2),
  ('sorridents', 'Profilaxia e claramento', 'Fluor gél neutro', 2, 3),
  ('sorridents', 'Profilaxia e claramento', 'Clareador de consultório', 2, 3),
  ('sorridents', 'Prótese', 'Alginato Hydrogum', 5, 2),
  ('sorridents', 'Prótese', 'Gesso Especial tipo IV', 5, 2),
  ('sorridents', 'Prótese', 'Gesso Pedra tipo III', 4, 2),
  ('sorridents', 'Prótese', 'Alginato comum', 4, 3),
  ('sorridents', 'Prótese', 'Kit Perfill', 1, 0),
  ('sorridents', 'Prótese', 'Pino De Fibra De Vidro 0,5', 1, 0),
  ('sorridents', 'Prótese', 'Pino De Fibra De Vidro 1', 1, 0),
  ('sorridents', 'Prótese', 'Lâmina de Cera 7', 2, 2),
  ('sorridents', 'Prótese', 'Dente de Estoque Anteriores cor 66 / 69/62', 2, 2),
  ('sorridents', 'Prótese', 'Fio Retrator 00', 1, 1),
  ('sorridents', 'Prótese', 'silano', 1, 1),
  ('sorridents', 'Prótese', 'Acrilico AutoPolimerizante rosa', 1, 1),
  ('sorridents', 'Prótese', 'Acrílico Líquido', 1, 1),
  ('sorridents', 'Prótese', 'Ácido Fluorídrico 10%', 2, 2),
  ('sorridents', 'Prótese', 'COREGA', 1, 1),
  ('sorridents', 'Prótese', 'Allcem Cimento Resinoso base + catalisador', 2, 3);
